name: atomate2-openmm
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - openmm
  - openff-toolkit # pymatgen-io-openmm
  - MDAnalysis # pymatgen-io-openmm
  - atomate2
  - jobflow
  - pip:
      - pytest
      - pytest-cov
      - pandas
#      - pymatgen
      - pymatgen-io-openmm @ git+https://github.com/orionarcher/pymatgen-io-openmm.git
