name: atomate2-openmm
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytest
  - openmm
  - openff-toolkit # pymatgen-io-openmm
  - MDAnalysis # pymatgen-io-openmm
  - atomate2
  - jobflow
  - pandas
  - pymongo
  - pip:
      - pymatgen
      - pymatgen-io-openmm @ git+ssh://git@github.com/orionarcher/pymatgen-io-openmm.git
      - erdantic
      - pytest-cov
