name: atomate2-openmm-test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytest
  - pymatgen
  - openmm
  - openff-toolkit # pymatgen-io-openmm
  - MDAnalysis # pymatgen-io-openmm
  - atomate2
  - jobflow
  - pip:
      - git+ssh://git@github.com/oriosnarcher/pymatgen-io-openmm.git