name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: 3.9
          auto-activate-base: false
      - name: Install conda openmm
        shell: bash -l {0}
        run: |
          conda install -c conda-forge openmm==openmm==8.0.0
      - name: Install conda openff-toolkit
        shell: bash -l {0}
        run: |
          conda install -c conda-forge openff-toolkit==0.12.1
      - name: Install conda MDAnalysis
        shell: bash -l {0}
        run: |
          conda install -c conda-forge MDAnalysis==2.4.3
      - name: Install conda atomate2
        shell: bash -l {0}
        run: |
          conda install -c conda-forge atomate2==0.0.10
      - name: Install conda jobflow
        shell: bash -l {0}
        run: |
          conda install -c conda-forge jobflow==0.1.11
      - name: Install pip pymatgen-io-openmm
        shell: bash -l {0}
        run: |
          pip install git+https://github.com/orionarcher/pymatgen-io-openmm.git
      - name: Install pip pymatgen-io-openmm
        shell: bash -l {0}
        run: |
          pip install pytest
      - name: Install pip pytest
        shell: bash -l {0}
        run: |
          pip install pytest
      - name: Install pip pytest-cov
        shell: bash -l {0}
        run: |
          pip install pytest-cov
      - name: Install pip pandas
        shell: bash -l {0}
        run: |
          pip install pandas
      - name: Install pip pymatgen-io-openmm
        shell: bash -l {0}
        run: |
          pip install .
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run pytest
        shell: bash -l {0}
        run: |
          conda install pytest
          pytest
