name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install conda dependencies
        run: |
          echo YOOO $CONDA
          source ~/anaconda3/etc/profile.d/conda.sh
          $CONDA/bin/conda create -n myenv python=3.8
#          $CONDA/bin/conda init bash
          $CONDA/bin/conda activate myenv
          $CONDA/bin/conda install -c conda-forge pip --yes
          $CONDA/bin/conda install -c conda-forge openmm --yes
          $CONDA/bin/conda install -c conda-forge openff-toolkit --yes
          $CONDA/bin/conda install -c conda-forge MDAnalysis --yes
          $CONDA/bin/conda install -c conda-forge atomate2 --yes
          $CONDA/bin/conda install -c conda-forge jobflow --yes
          $CONDA/bin/conda install -c conda-forge pymongo --yes
      - name: Install pip dependencies
        run: |
          $CONDA/bin/conda activate myenv
          pip install pymatgen
          pip install git+ssh://git@github.com/orionarcher/pymatgen-io-openmm.git
          pip install erdantic
          pip intall pytest
          pip install pytest-cov
          pip instal pandas
      - name: Test with pytest
        run: |
          $CONDA/bin/pytest
