# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: atomate2-openmm tests and linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Miniconda
        run: |
          wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda update --all --yes

      - name: Create conda environment from file
        run: |
          conda create -n myenv python=3.=8
          conda activate myenv
          conda install -c conda-forge pip pytest openmm openff-toolkit MDAnalysis atomate2 jobflow pandas pymongo

      - name: Install other dependencies
        run: |
          pip install pymatgen
          pip install git+ssh://git@github.com/orionarcher/pymatgen-io-openmm.git
          pip install erdantic
          pip install pytest-cov
          pip install .

      - name: Run tests
        run: |
          pytest
